//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.0.0+9dfb300
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace zudioclone.models.Models.PageModels
{
	/// <summary>Home</summary>
	[PublishedModel("home")]
	public partial class Home : PublishedContentModel, ICollections, IFooterlast, IHeaderlast
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		public new const string ModelTypeAlias = "home";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Home, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Home(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// bannerimagehome
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bannerimagehome")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Bannerimagehome => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "bannerimagehome");

		///<summary>
		/// blogheading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("blogheading")]
		public virtual string Blogheading => this.Value<string>(_publishedValueFallback, "blogheading");

		///<summary>
		/// campaignimage1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("campaignimage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Campaignimage1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "campaignimage1");

		///<summary>
		/// campaignimage2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("campaignimage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Campaignimage2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "campaignimage2");

		///<summary>
		/// campaignimage3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("campaignimage3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Campaignimage3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "campaignimage3");

		///<summary>
		/// campaignimage4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("campaignimage4")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Campaignimage4 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "campaignimage4");

		///<summary>
		/// campaign-title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("campaignTitle")]
		public virtual string CampaignTitle => this.Value<string>(_publishedValueFallback, "campaignTitle");

		///<summary>
		/// homecontent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("homecontent")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Homecontent => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "homecontent");

		///<summary>
		/// homerightcontentheading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("homerightcontentheading")]
		public virtual string Homerightcontentheading => this.Value<string>(_publishedValueFallback, "homerightcontentheading");

		///<summary>
		/// Beauty
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("beauty")]
		public virtual string Beauty => global::zudioclone.models.Models.PageModels.Collections.GetBeauty(this, _publishedValueFallback);

		///<summary>
		/// ethnic
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ethnic")]
		public virtual string Ethnic => global::zudioclone.models.Models.PageModels.Collections.GetEthnic(this, _publishedValueFallback);

		///<summary>
		/// Footwear
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footwear")]
		public virtual string Footwear => global::zudioclone.models.Models.PageModels.Collections.GetFootwear(this, _publishedValueFallback);

		///<summary>
		/// kids
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("kids")]
		public virtual string Kids => global::zudioclone.models.Models.PageModels.Collections.GetKids(this, _publishedValueFallback);

		///<summary>
		/// Loungewear
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("loungewear")]
		public virtual string Loungewear => global::zudioclone.models.Models.PageModels.Collections.GetLoungewear(this, _publishedValueFallback);

		///<summary>
		/// men
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("men")]
		public virtual string Men => global::zudioclone.models.Models.PageModels.Collections.GetMen(this, _publishedValueFallback);

		///<summary>
		/// women
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("women")]
		public virtual string Women => global::zudioclone.models.Models.PageModels.Collections.GetWomen(this, _publishedValueFallback);

		///<summary>
		/// contact
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contact")]
		public virtual string Contact => global::zudioclone.models.Models.PageModels.Footerlast.GetContact(this, _publishedValueFallback);

		///<summary>
		/// contacttitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contacttitle")]
		public virtual string Contacttitle => global::zudioclone.models.Models.PageModels.Footerlast.GetContacttitle(this, _publishedValueFallback);

		///<summary>
		/// copyright
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("copyright")]
		public virtual string Copyright => global::zudioclone.models.Models.PageModels.Footerlast.GetCopyright(this, _publishedValueFallback);

		///<summary>
		/// fashion
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fashion")]
		public virtual string Fashion => global::zudioclone.models.Models.PageModels.Footerlast.GetFashion(this, _publishedValueFallback);

		///<summary>
		/// follow
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("follow")]
		public virtual string Follow => global::zudioclone.models.Models.PageModels.Footerlast.GetFollow(this, _publishedValueFallback);

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::zudioclone.models.Models.PageModels.Footerlast.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// Contact Us: this is Contact Us page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactus")]
		public virtual string Contactus => global::zudioclone.models.Models.PageModels.Headerlast.GetContactus(this, _publishedValueFallback);

		///<summary>
		/// contactuslink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactuslink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Contactuslink => global::zudioclone.models.Models.PageModels.Headerlast.GetContactuslink(this, _publishedValueFallback);

		///<summary>
		/// Login
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("login")]
		public virtual string Login => global::zudioclone.models.Models.PageModels.Headerlast.GetLogin(this, _publishedValueFallback);

		///<summary>
		/// loginlink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("loginlink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Loginlink => global::zudioclone.models.Models.PageModels.Headerlast.GetLoginlink(this, _publishedValueFallback);

		///<summary>
		/// Logout
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("logout")]
		public virtual string Logout => global::zudioclone.models.Models.PageModels.Headerlast.GetLogout(this, _publishedValueFallback);

		///<summary>
		/// logoutlink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("logoutlink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Logoutlink => global::zudioclone.models.Models.PageModels.Headerlast.GetLogoutlink(this, _publishedValueFallback);

		///<summary>
		/// Register
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("register")]
		public virtual string Register => global::zudioclone.models.Models.PageModels.Headerlast.GetRegister(this, _publishedValueFallback);

		///<summary>
		/// registerlink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("registerlink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Registerlink => global::zudioclone.models.Models.PageModels.Headerlast.GetRegisterlink(this, _publishedValueFallback);

		///<summary>
		/// Search: this is search page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("search")]
		public virtual string Search => global::zudioclone.models.Models.PageModels.Headerlast.GetSearch(this, _publishedValueFallback);

		///<summary>
		/// searchlink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchlink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Searchlink => global::zudioclone.models.Models.PageModels.Headerlast.GetSearchlink(this, _publishedValueFallback);

		///<summary>
		/// Zudio Blog: this is blog page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ZBlog")]
		public virtual string Zblog => global::zudioclone.models.Models.PageModels.Headerlast.GetZblog(this, _publishedValueFallback);

		///<summary>
		/// zbloglink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("zbloglink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Zbloglink => global::zudioclone.models.Models.PageModels.Headerlast.GetZbloglink(this, _publishedValueFallback);

		///<summary>
		/// z stories: this is homepage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("Zstory")]
		public virtual string Zstory => global::zudioclone.models.Models.PageModels.Headerlast.GetZstory(this, _publishedValueFallback);

		///<summary>
		/// zstorylink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("zstorylink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Zstorylink => global::zudioclone.models.Models.PageModels.Headerlast.GetZstorylink(this, _publishedValueFallback);

		///<summary>
		/// Zudio near you
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("Zudionear")]
		public virtual string Zudionear => global::zudioclone.models.Models.PageModels.Headerlast.GetZudionear(this, _publishedValueFallback);

		///<summary>
		/// zudionearyoulink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("zudionearyoulink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Zudionearyoulink => global::zudioclone.models.Models.PageModels.Headerlast.GetZudionearyoulink(this, _publishedValueFallback);

		///<summary>
		/// Z world: this is about page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("Zworld")]
		public virtual string Zworld => global::zudioclone.models.Models.PageModels.Headerlast.GetZworld(this, _publishedValueFallback);

		///<summary>
		/// zworldlink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.0+9dfb300")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("zworldlink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Zworldlink => global::zudioclone.models.Models.PageModels.Headerlast.GetZworldlink(this, _publishedValueFallback);
	}
}
